=begin pod

=head1 NAME

Math::FractionalPart - blah blah blah

=head1 SYNOPSIS

=begin code :lang<raku>
use Math::FractionalPart :afrac;
say (afrac -3.2); # Output <<0.2>>
say (frac -3.2);  # Output <<-0.2>>
=end code

=head1 DESCRIPTION

Math::FractionalPart provides several routines to operate with the
fractional parts of a number:

There are three different algebraic functions that operate on numbers
and return their fractional parts. They all return the same result
when operating on non-negative numbers, but all three return different
results when operating on negative numbers. See the following
references:

=item1 1. Wikipedia article on L<Fractional Part|https://en.m.wikipedia.org/wiki/Fractional_part>
=item1 2. Wolfram article on L<Fractional Part|https://mathworld.wolfram.com/FractionalPart.html>
=item1 3. I<Celestial Calculations: A Gentle Introduction to Computational Astronomy>, J. L. Lawrence, 2018, MIT Press.

=begin table
Name  | Formula                                     | Example           | Notes
---   | ---                                         | ---               | ---
frac  | x - E<0x230a>xE<0x230b>                     | frac(-1.3): 0.7   | 1
afrac | \|x\| - E<0x230a>\|x\|E<0x230b>             | afrac(-1.3): 0.3  | 2
ofrac | x - E<0x230a>\|x\|E<0x230b>E<0x22c5>sign(x) | ofrac(-1.3): -0.3 | 3
=end table

Notes
=item1 1. See Ref 1, *frac* version 1 (per Graham, Knuth, et alii, 1992).
=item1 2. See Ref 1, *frac* version 2 (per Dainith, 2004); Ref 3, p. 7. Consider mnemonic 'a' for 'absolute value' or 'astronomical'.
=item1 3. See Ref 1, *frac* version 3 (an *odd function*); Ref 2: Wolfram's *FractionPart* function. Consider mnemonic 'o' for 'odd function'.

=head1 AUTHOR

Tom Browder <tbrowder@cpan.org>

=head1 COPYRIGHT AND LICENSE

E<0x00a9> 2021 Tom Browder

This library is free software; you can redistribute it or modify it under the Artistic License 2.0.

=end pod
